// src/report.js
import { appendFile, writeFile, mkdir, access } from 'node:fs/promises';
import { homedir } from 'node:os';
import { join, dirname } from 'node:path';
import { readHistory } from './history.js';

export function getReportPath(config) {
  const dir = (config.reportDir ?? join(homedir(), '.config', 'dnc'))
    .replace(/^~/, homedir());
  return join(dir, 'do-not-call-reports.md');
}

export async function checkDuplicate(callerPhone) {
  const history = await readHistory(Number.MAX_SAFE_INTEGER);
  const matches = history.filter(r => r.success && r.callerPhone === callerPhone);
  return matches.length > 0 ? matches[matches.length - 1] : null;
}

function formatPhone(digits) {
  return `(${digits.slice(0, 3)}) ${digits.slice(3, 6)}-${digits.slice(6)}`;
}

function toISODate(mmddyyyy) {
  if (!mmddyyyy) return null;
  const [m, d, y] = mmddyyyy.split('/');
  return `${y}-${m.padStart(2, '0')}-${d.padStart(2, '0')}`;
}

function formatEntry(record) {
  const dateStr = toISODate(record.callDate) ?? record.timestamp.slice(0, 10);
  const timeStr = record.callTime ?? record.timestamp.slice(11, 16);
  const callType = record.callType === 'robocall' ? 'Robocall' : 'Live person';
  const topic =
    record.callTopic === 'Other' && record.callTopicOther
      ? `Other — ${record.callTopicOther}`
      : (record.callTopic ?? '—');
  const address =
    [record.address, record.city, record.state, record.zip].filter(Boolean).join(', ') || '—';

  return [
    `## ${dateStr} ${timeStr} — ${formatPhone(record.callerPhone)}`,
    '',
    `- **Filed:** ${new Date(record.timestamp).toLocaleString()}`,
    `- **Caller number:** ${formatPhone(record.callerPhone)}`,
    `- **Call date:** ${record.callDate ?? '—'} at ${record.callTime ?? '—'}`,
    `- **Call type:** ${callType}`,
    `- **Topic:** ${topic}`,
    `- **My number:** ${record.myPhone ? formatPhone(record.myPhone) : '—'}`,
    `- **Name:** ${[record.firstName, record.lastName].filter(Boolean).join(' ') || '—'}`,
    `- **Address:** ${address}`,
    `- **Comment:** ${record.comment ?? '—'}`,
    `- **Screenshot:** ${record.screenshotPath ?? '—'}`,
    '',
    '---',
  ].join('\n');
}

const HEADER =
  '# Do Not Call Complaints\n\n' +
  '> Auto-generated by `dnc`. To rebuild from history, run `dnc --generate-report`.\n\n' +
  '---\n';

export async function appendReport(record, config) {
  const path = getReportPath(config);
  await mkdir(dirname(path), { recursive: true });
  let exists = false;
  try { await access(path); exists = true; } catch {}
  const entry = '\n' + formatEntry(record) + '\n';
  if (!exists) {
    await writeFile(path, HEADER + entry);
  } else {
    await appendFile(path, entry);
  }
}

export async function generateReport(config) {
  const history = await readHistory(Number.MAX_SAFE_INTEGER);
  const successful = history.filter(r => r.success);
  const path = getReportPath(config);
  await mkdir(dirname(path), { recursive: true });
  const body =
    successful.length > 0
      ? successful.map(r => '\n' + formatEntry(r)).join('\n') + '\n'
      : '\n_No complaints filed yet._\n';
  await writeFile(path, HEADER + body);
  return { path, count: successful.length };
}
